nextstrain/pathogen-repo-guide

- ingest/README.md
- ingest/Snakefile
- ingest/config/defaults.yaml
- ingest/config/nextclade_field_map.tsv
- ingest/rules/nextclade.smk
Adds template for optional rules to run Nextclade as a part of the ingest workflow. 
The Nextclade rules are optional because not every pathogen will have a Nextclade dataset to be able to run Nextclade as part of ingest. 
~This wraps up the "core" ingest workflow that produces the curated metadata and sequences.~
Maybe not, we should probably add Biosample data to the ingest template.
> Add Nextclade to ingest

- ingest/README.md
- ingest/config/defaults.yaml
- ingest/rules/curate.smk
- ingest/vendored/.github/workflows/ci.yaml
- ingest/vendored/.gitrepo
- ingest/vendored/README.md
- ingest/vendored/tests/transform-strain-names/transform-strain-names.t
- ingest/vendored/transform-strain-names
Pulling in the latest [nextstrain/ingest](https://github.com/nextstrain/ingest) before I make Nextstrain automation profiles that use the ingest scripts. Turns out the template already had the latest scripts required for Nextstrain automation rules. This just pulled in the centralized `transform-strain-names` script, which I've added to the curation pipeline.
> Update ingest vendored

- ingest/rules/nextclade.smk
The `awk NR>1` would have dropped the initial line in a `nextclade_field_map.tsv` file without a comment block header.  This commit fixes that.
> fix: dropping the first line in a bare nextclade_field_map.tsv

- ingest/config/defaults.yaml
- ingest/rules/fetch_from_ncbi.smk
Instead of hard-coding the list of NCBI Datasets fields in the workflow, just provide the list via the default config. This makes it easy to customize which fields to include and makes it very obvious that field_map config for the the curation pipeline is changing the names of these NCBI fields.
This includes a change in the `format_ncbi_dataset_report` rule to use the provided fields as the header so that we do not have to do a separate renaming of the NCBI column names back to the computer friendly mneumonics.
Prompted by my review of dengue ingest PR https://github.com/nextstrain/dengue/pull/13#discussion_r1376652158
> ingest: simplify NCBI Datasets fields config

- ingest/rules/fetch_from_ncbi.smk
Some of the fields in NCBI contain values with internal double quotes like:
```
UMR "Emergence des Pathologies Virales" (EPV: Aix-Marseille Univ-IRD190-INSERM1207-EHESP-IHU Mediterranee Infection)
```
which causes csvtk to throw error:
```
bare `"` in non-quoted-field.
```
The suggested fix is to add a `-l` flag shown in case 7 at:
https://bioinf.shenwei.me/csvtk/usage/#:~:text=7.-,If%20double%2Dquotes%20exist%20in%20fields%20not%20enclosed%20with%20double,%2Dquotes%22%20to%20fix%20it.
> handle bare quotes in fields

- ingest/rules/nextclade.smk
- nextclade/profiles/test_dataset/test_dataset.smk
Soon we will release nextclade v3. Once nextclade v3 hits bioconda, workflows that rely on v2 syntax will break. To prevent this, this PR makes it explicit that the syntax used is for v2 and that the v2 binary nextclade2 should be used.
This binary is in both the nextstrain-base docker image and in the conda-base managed conda environment.
Users who don't use either will have to add nextclade2 to the path.
Over the next few weeks, we will transition repos to use nextclade3. The reason to add nextclade2 now is so that workflows don't break if they haven't yet transitioned to nextclade3 at the time of v3 release. It also makes it easy to search which workflows need to be changed.
> Version nextclade binary for transition, i.e. nextclade -> nextclade2

- ingest/README.md
- ingest/Snakefile
- nextclade/README.md
- nextclade/Snakefile
- phylogenetic/README.md
- phylogenetic/Snakefile
Workflows must be run from the top level pathogen repo directory in order for them to have access to the `shared` directory in the containerized runtimes. After some external testing of different ways to invoke the workflows with the Nextstrain CLI¹, I've decided to add the hardcoded `workdir` directive in each workflow's main Snakefile.
Then the default workflows can be run with:
```
nextstrain build . -s phylogenetic/Snakefile
nextstrain build . -s ingest/Snakefile
nextstrain build . -s nextclade/Snakefile
```
With this uniform organization of workflows across pathogens, we can then move the Snakemake option to behind the scenes within the Nextclade CLI.
This will allow us to have a workflow manager agnostic option, such as:
```
nextstrain build --workflow phylogenetic .
```
¹ …
> workflows: Add hardcoded `workdir` directives

- ingest/README.md
- nextclade/README.md
- nextstrain-pathogen.yaml
- phylogenetic/README.md
This is currently an empty file to indicate the top level pathogen repo. The inclusion of this file allows the `nextstrain build` invocation to work from any directory regardless of runtime.
See https://github.com/nextstrain/cli/pull/355 for more details.
> Add top level nextstrain-pathogen.yaml file

- ingest/defaults/config.yaml
Simplify the starting process for setting up the ingest workflow by providing default values for the config parameters.
This leaves first time users with two major decisions in the config.yaml:
1. Do I use NCBI Virus or Entrez?
2. Do I include Nextclade?
Resolves https://github.com/nextstrain/pathogen-repo-guide/issues/4
> ingest: Add default values to config.yaml

- ingest/build-configs/nextstrain-automation/upload.smk
Fixes error reported by @kimandrews on Slack:
```
$ nextstrain build ingest upload_all --configfile build-configs/nextstrain-automation/config.yaml -n
Config file defaults/config.yaml is extended by additional config specified via the command line.
NameError in file /nextstrain/build/ingest/build-configs/nextstrain-automation/upload.smk, line 23:
name 'wildcards' is not defined
```
> ingest/nextstrain-automation: Fix upload_to_s3

- ingest/README.md
- ingest/Snakefile
- ingest/defaults/config.yaml
- ingest/defaults/nextclade_config.yaml
It is unintuitive to have to remove default configs on the first run of the ingest workflow, so move the Nextclade configs to a separate config YAML that can be optionally used in `nextstrain build`.
Note that once the Nextclade dataset is stabilized for a pathogen, it then makes sense to move the configs into the default config.yaml
Prompted by https://github.com/nextstrain/docs.nextstrain.org/issues/179
> ingest: Move Nextclade configs to separate YAML

- ingest/build-configs/nextstrain-automation/README.md
Add a README.md to describe the use of this build-config and to provide some instructions on how to use it for internal Nextstrain team members.
> ingest/build-configs/nextstrain-automation: Add README

- .gitattributes
Nextstrain pathogen repositories should be standardized include `.gitattributes` for force line endings to be LF.
We've run into issues in the past with Windows users running into workflow errors because of Windows line endings (CRLF):
https://github.com/nextstrain/mpox/commit/def0a713ae699fc313b549840e7f41f3033e3467 
https://github.com/nextstrain/seasonal-flu/commit/202263aecf47e1906875bd2d2e80d7b0c82039cd
> Add .gitattibutes to force line endings to be LF

- ingest/README.md
- ingest/rules/fetch_from_ncbi.smk
Provides an easy way for first time users to get the full
uncurated metadata from NCBI Datasets commands by running the
ingest workflow with the specified target `dump_ncbi_dataset_report`.
They can then inspect and explore the raw data to determine if they
want to configure the workflow to use additional fields from NCBI.
The rule is added to `fetch_from_ncbi.smk` to make it easy to run
without additional configs. Note that it is not run as part of the
default workflow and only intended to be used as a specified target.
Prompted by @jameshadfield in review of the tutorial¹ and
resolves https://github.com/nextstrain/pathogen-repo-guide/issues/30.
¹ https://github.com/nextstrain/docs.nextstrain.org/pull/195 (comment)
> ingest: Provide target for raw metadata from NCBI Datasets

- ingest/defaults/config.yaml
- ingest/rules/fetch_from_ncbi.smk
Resolves https://github.com/nextstrain/pathogen-repo-guide/issues/39
Create a new accession field without the version number so that annotations do not need to be updated when the version number is updated.
Related to https://github.com/nextstrain/measles/issues/24
> ingest: Create new accession field without version

- CHANGELOG.md
- ingest/Snakefile
- ingest/defaults/config.yaml
- ingest/rules/fetch_from_ncbi.smk
- phylogenetic/Snakefile
This fixes various typos, misspellings, grammatical issues that I noticed while reading through the repository. It also contains a few additions or rephrasing. 
I have structured this so that each type of change is in a single commit, so that if any of the changes are objectionable or undesired, rebasing them out should be trivial.
> Misc tpyoes

- docs/nextstrain-internal/README.md
- docs/nextstrain-internal/automated-pathogen-workflows.md
- docs/nextstrain-internal/pathogen-repo-ci.md
I didn't want to take the time to set up of full Read the Docs project since I'm not even sure that's needed. 
Just using Markdown files to document:
1. the CI workflow
2. automating pathogen repo workflows
Resolves https://github.com/nextstrain/pathogen-repo-guide/issues/10
> Add docs for internal Nextstrain team

- ingest/defaults/nextclade_config.yaml
- ingest/defaults/nextclade_field_map.tsv
- ingest/rules/nextclade.smk
Various small fixes for the Nextclade rules of the ingest workflow. 
See commits for details. 
Resolves https://github.com/nextstrain/pathogen-repo-guide/issues/47
Related to https://github.com/nextstrain/private/issues/97
> Ingest nextclade updates

- ingest/defaults/config.yaml
Enables filtering out lab-host strains to focus on real-time genomic surveillance strains. I've needed to filter out `PAT` and other lab-host strains in 
* [dengue](https://github.com/nextstrain/dengue/commit/af38fb000155029d6a3a4f8f5fee7055316dfd5a)
* [lassa](https://github.com/nextstrain/lassa/pull/25)
* and again in WNV
I'm adding the `is_lab_host` column to the `pathogen-repo-guide` since we usually want to be able to filter these out of real-time phylogenetic trees, and so I may one-day stop forgetting to add this column...
Resolves https://github.com/nextstrain/pathogen-repo-guide/issues/60
> Adds a recommended `is_lab_host` column to the ingested metadata.tsv file

- nextclade/build-configs/test-dataset/test_dataset.smk
- nextclade/rules/export.smk
1. nextclade/export: Update REQUIRED INPUTS for Nextclade v3
2. Update example test_dataset command to `nextclade3`
Resolves https://github.com/nextstrain/pathogen-repo-guide/issues/69
> Update nextclade workflow docs for v3

- ingest/defaults/config.yaml
Switch `authors` to `full_authors` and `abbr_authors` to `authors` so that the abbreviated author field is used by `augur export` in the phylogenetic workflow.
Making this the default in pathogen repos until we get around to https://github.com/nextstrain/augur/issues/1685. 
Similar to changes in https://github.com/nextstrain/mpox/pull/295.
> ingest: Switch to `full_authors` and `authors` fields

- ingest/rules/curate.smk
- ingest/rules/fetch_from_ncbi.smk
- ingest/rules/nextclade.smk
Following Nextstrain data format docs to update handling of TSVs with `csvtk`.¹ Instead of going through extra `csv2tsv`/`csvtk fix-quotes` commands, just replace `tsv-select` with `csvtk`. Note that NCBI uses IANA TSVs,² so the `dataformat` output must go through `csvtk fix-quotes` to be properly quoted as CSV-like TSVs.
- `tsv-select` to subset columns is directly replaced with `csvtk cut -t`.
- `tsv-select` to reorder columns is replaced with `csvtk mutate --at 1` to insert the new `accession` column as the first column.
¹ <https://docs.nextstrain.org/en/latest/reference/data-formats.html#id1> 
² <https://www.ncbi.nlm.nih.gov/datasets/docs/v2/reference-docs/file-formats/metadata-files/about-json-and-tabular/>
Resolves https://github.com/nextstrain/pathogen-repo-guide/issues/66
> ingest: properly handle TSVs with `csvtk`

- ingest/defaults/config.yaml
- ingest/rules/curate.smk
Add URL column during ingest so the node call out works automatically. Attempting the `jq` method
* https://github.com/nextstrain/pathogen-repo-guide/issues/76
> Ingest: Derive URL column during ingest

- .github/workflows/pre-commit.yaml
Running on push to all branches is both unnecessary (notifications for failing checks are mostly noise when pushing work-in-progress to a branch) and not enough (doesn't cover pushes to fork PRs).
I've copied the triggers that we use for almost all CI workflows in Nextstrain.
Thought of this while reviewing fork PRs in measles, where pre-commit wasn't running.
> Update pre-commit trigger

- ingest/Snakefile
- ingest/rules/config.smk
- nextclade/Snakefile
- nextclade/rules/config.smk
- phylogenetic/Snakefile
- phylogenetic/rules/config.smk
- shared/vendored/.github/workflows/pre-commit.yaml
- shared/vendored/.gitrepo
- shared/vendored/README.md
- shared/vendored/snakemake/config.smk
Made the same change across all workflows to write the Snakemake config to an output file with the shared `write_config` function. Calling the function on a per-workflow basis to leave room for workflow specific config manipulation _before_ writing the config.
https://github.com/nextstrain/pathogen-repo-guide/issues/18
> Write config to file
